import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <div className={styles.banter}>
          <h1>ENJOY THE WORLD</h1>
          <button>EXPLORE &#8594;</button>
        </div>
        <div className={styles.country}>
          <h2>VIETNAM</h2>
          <div className={styles.carousel}></div>
        </div>
      </main>
    </div>
  )
}

export default Home
