import axios from 'axios';
import { gql } from '@apollo/client';
import client from '../lib/apollo';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import Navbar from '../components/navbar';
import ImageSlider from '../components/imageSlider';
import styles from '../styles/Home.module.scss';

interface homeProps {
  countryData: [countryData]
}
interface countryData {
  name: string
  picture: HomePicture 
}

interface HomePicture{
  portrait: Picture
  landscape: Picture
}
interface Picture {
  link: string
}

const Home: NextPage<homeProps> = ( { countryData }) => {
  const [currentSlide,setCurrentSlide] = useState<number>(0);
  const [currentCountry,setCurrentCountry] = useState<string>(countryData[0].name);
  const [currentMainTheme,setCurrentMainTheme] = useState<string>(countryData[0].picture.landscape.link);
  const slides: Array<string> = [];
  countryData.map((country) => slides.push(country.picture.portrait.link));
  function changeCountryInfo(index:number){
    setCurrentCountry(countryData[currentSlide].name);
    setCurrentMainTheme(countryData[currentSlide].picture.landscape.link);
  }
  useEffect(()=>{
    changeCountryInfo(currentSlide);
  },[currentSlide]);
  useEffect(()=> {
    console.log(currentMainTheme)
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={{backgroundImage: `url(${currentMainTheme})`}}>
        <Navbar/>
        <div className={styles.banter}>
          <h2>ENJOY THE</h2>
          <h1>WORLD</h1>
          <button>EXPLORE NOW &#8594;</button>
        </div>
        <div className={styles.country}>
          <h2>{currentCountry}</h2>
          <ImageSlider slides = { slides } changeSlide = {setCurrentSlide}/>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(){
  const { data } = await client.query({
    query: gql`
     query Countries {
      countries {
        name
        picture {
          portrait {
            link
        }
        landscape {
          link
        }
    }
  }
}
    `
  }) 
  return {
    props: {
      countryData:data.countries,
    },
  }
}
export default Home
